# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a29e882469d150adbc3c9407a0be0c7e936c1a8038702a1b7a34c254401d73a7adbe1a8bada28040cd9f2d9ab1ac1cc252d904fa5ea1b2827248adc7082c0656

test:
  secret_key_base: 1594075473c025defbc102991b66310d0a2f1cb9fea98ddea118b9a77d233025250d14ad742005c4d03e76a45cf15708f80d9d34a4b6508bbe43d5088e8bd310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
